=  Core 核心组件
作者：肖鹏 <13910818313@163.com>

:source-highlighter: highlight.js
:imagesdir: images
:sourcedir: ../../main/java
:build-gradle: ../../../build.gradle

[[介绍]]
== 介绍
是基础组件,提供框架层的底层支持、项目框架的基础功能、 系统错误整体处理器等功能

[[版本]]

*  0.2.1

[[使用]]
== 使用
gradle中
[source,gradle]
----
    implementation('io.github.baseinsight:core-starter:x.x.x')
----

TIP: 需要添加repositories:
maven { url "https://s01.oss.sonatype.org/content/repositories/snapshots/" }


[[描述]]
== 功能描述

=== 统一的错误处理

统一输出错误json, 是实例化的ApiError类的json字符串输出。

=== entity 类的json 输出

系统默认使用spring MVC内置的jacksonJSON进行json转换输出。

==== 使用@JsonFormat注解指明Date类型字段转换为json的规则，如下：

    @JsonFormat(pattern = "yyyy-MM-dd",timezone="GMT+8")
    Date loginTime;

==== 使用@JsonSerialize(using=EntitySimpleJsonSerializer.class)注解来指明Entity类的外键对象json规则，默认生成id，label，class三个属性（序列id、显示label，class类名）

	@JsonSerialize(using=EntitySimpleJsonSerializer.class)
	BaseUser baseUser;

==== 使用@EntitySimpleJsonFormat注解配合JsonSerialize来定制化Entity类的外键对象json规则,支持values和ignores两种字段设置方式

	@JsonSerialize(using=EntitySimpleJsonSerializer.class)
	@EntitySimpleJsonFormat(ignores=['version','dateCreated','lastUpdated'])
	BaseUser baseUser;


[[提供辅助类]]
== 提供辅助类

=== annotation 注解

==== FullRestController 注解

用于提供controller类的自动RequestMapping映射，从而使的系统开发人员不必再手工设置RequestMapping和指定view视图的名称。


==== EntitySimpleJsonFormat注解

是针对jacksonJson转换对象为json时使用的注解，配合JsonSerialize来定制化Entity类的外键对象json规则,支持values和ignores两种字段设置方式

	@JsonSerialize(using=EntitySimpleJsonSerializer.class)
	@EntitySimpleJsonFormat(ignores=['version','dateCreated','lastUpdated'])
	BaseUser baseUser;

=== 辅助服务类

==== SpringUtils类

SpringUtils类静态方法
[format="csv", options="header"]
|===
    action name,描述
    getApplicationContext() ,   获取 应用context
    getResource(String resource) , 获取资源
    getBean(String name)   ,         获取bean
    getConfiginfo(String key)  ,        获取application.yml的配置信息
    getI18nMessage(String code，List arguments，String defaultMessage，Locale locale)  , 获取i18n资源的信息
    getI18nMessage(String code，List arguments，String defaultMessage) , 获取i18n资源的信息
    getI18nMessage(String code，List arguments)  , 获取i18n资源的信息
    getI18nMessage(String code) , 获取i18n资源的信息
    publishEvent(Object event) , 发布事件
    publishEvent(AppEvent event) , 发布系统事件
    addApplicationListener(ApplicationListener<?> listener) , 添加事件监听（订阅事件）
|===

== 系统部署

=== 默认支持spring boot的标准模式部署， 因此只需要打包运行即可。

运行开发工具的gradle的build或buildDependents,查看工程的build/libs目录，可以看到生成的jar文件。

在生产环境中运行命令java -jar 命令。

[source,java]
----
java -jar demo.jar
----


== linux环境及docker的urandom问题

/dev/random和/dev/urandom是Linux系统中提供的随机伪设备，这两个设备的任务，是提供永不为空的随机字节数据流。很多解密程序与安全应用程序（如SSH Keys,SSL Keys等）需要它们提供的随机数据流。

这两个设备的差异在于：/dev/random的random pool依赖于系统中断，因此在系统的中断数不足时，/dev/random设备会一直封锁，尝试读取的进程就会进入等待状态，直到系统的中断数充分够用, /dev/random设备可以保证数据的随机性。/dev/urandom不依赖系统的中断，也就不会造成进程忙等待，但是数据的随机性也不高。

war 包模式运行会碰到这类问题影响性能,建议增加-Djava.security.egd=file:/dev/./urandom参数避免之.

示例如下:
[source,java]
----
#!/bin/sh
java -Djava.security.egd=file:/dev/./urandom -jar /app/application.war
----

TIP: 也可以通过在docker中部署解压后的应用程序，绕开此问题


== 事件机制

核心默认提供事件AppStartupEvent、AppShutdown和事件基类AppEvent，编写相关的listener可订阅相关事件.

TIP: 若订阅基类AppEvent事件，则能收到全部框架发布的事件。

=== 订阅事件

==== 使用独立listener类订阅

编写listener类来订阅事件

[source,java]
----
@Configuration
class NewAppListener implements ApplicationListener<AppStartupEvent> {
    @Override
    void onApplicationEvent(AppStartupEvent event) {
        System.out.println("i receiver system startup event:"+event.toString());
    }
}
----

==== 简便方法订阅

也可使用SpringUtils辅助类的静态方法订阅

[source,java]
----
        SpringUtils.addApplicationListener(new ApplicationListener<AppEvent>() {
            @Override
            public void onApplicationEvent(AppEvent event) {
                System.out.println("i receiver one system event: "+event.toString());
            }
        });
----

=== 发布事件

使用SpringUtils辅助类的静态方法可以发布事件
[source,groovy]
----
SpringUtils.publishEvent(new AppEvent('测试事件'));
----
