= 关于baseInsight
author: 肖鹏 <13910818313@163.com>
2023-06-07

:source-highlighter: highlight.js
:imagesdir: images
:sourcedir: ../../main/java
:build-gradle: ../../../build.gradle

系统定位是快速开发的起步框架,目标是希望减少开发人员在框架层付出，精力聚焦于业务逻辑的实现。采用轻量化、组件式的设计模式来引导终端开发人员应对多变的WEB应用系统的开发。

为避免重复发明轮子，以集成成型的优质的开源框架为主要模式，采用微内核、多插件的形式，提供对业务场景的支持。
系统由内核core系统包和多个springboot-start构成一个完备的项目示例工程，辅以完备的在线文档（markdown或adoc）来指引开发人员。

[format="csv", options="header"]
|===
分类,推荐,说明
开发工具,idea intellij,
构建工具,gradle,
代码管理,git,
开发语言,java,
制品类型,docker,
CI/CD,jenkins,
配置文件类型,*.yml,
|===

== 制品库及引用方式

[format="csv", options="header"]
|===
分类,方法,说明
repository,    maven { url "https://s01.oss.sonatype.org/content/repositories/releases/" },
引用方式,    implementation('io.github.baseinsight:core-starter:0.2.1'),gradle
|===

== 基本组件

[format="csv", options="header"]
|===
名称,介绍,说明
核心组件,link:core.html[core-starter],
安全组件,link:springsecurity.html[plugin-springsecurity-starter],
缓存组件,link:cache.html[plugin-cache-starter],
redis组件,link:redis.html[plugin-redis-starter],
安全rest插件,link:springsecurity-rest.html[plugin-springsecurity-rest-starter],
安全rest-db插件,link:springsecurity-rest-db.html[plugin-springsecurity-rest-db-starter],
安全rest-redis插件,link:springsecurity-rest-redis.html[plugin-springsecurity-rest-redis-starter],
安全camunda插件,link:springsecurity-camunda.html[plugin-springsecurity-camunda-starter],
安全websocket插件,link:springsecurity-websocket.html[plugin-springsecurity-websocket-starter],
|===

== 开发经验
//JPA