= camunda 工作流插件
作者：肖鹏 <13910818313@163.com>

:source-highlighter: highlight.js
:imagesdir: images
:sourcedir: ../../main/java
:build-gradle: ../../../build.gradle

[[介绍]]
== 介绍
提供camunda 最新版本 7.20.0.alpha2 工作流的功能集成。
因为制品库org.camunda.bpm.springboot:camunda-bpm-spring-boot-starter:7.20.0.alpha2内置了javax.servlet,因此只能使用tomcat9部署，也因此只能适配springboot2.7.9; 而baseInsight框架使用springboot3.1.0，内置了tomcat10，迁移至jakarta.servlet等命名空间，因此研发此插件，补齐工作流引擎的初始配置，并与系统的springsecurity 默认集成.

[[版本历史]]

== 版本历史

*  0.0.7-SNAPSHOT

[[使用]]
== 使用

=== 使用gradle 插件

==== 添加插件
gradle中
[source,groovy]
----
    implementation('io.github.baseinsight:plugin-springsecurity-camunda-starter:x.x.x-SNAPSHOT')
----


== 日志跟踪

如果使用applicaton.yml中的配置
[source,yml]
----
logging.level.org.hibernate.SQL: TRACE
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
----

如果感觉不直观，无法确切跟踪camunda执行的sql语句，可开启logback （将resources目录下的logback.xmlbak更名为logback.xml即可）。
在其中添加语句：
[source,yml]
----
。。。。。。
<logger name="org.camunda.engine.impl.persistence.entity" level="DEBUG" />
。。。。。。
</configuration>
----

== 约定

默认系统有如下约定

=== service bean

默认插件将cumunda的服务注册为spring 的bean

具体功能api请参考camunda的相关文档

[format="csv", options="header"]
|===
name,描述,api
processEngine,流程引擎,org.camunda.engine.ProcessEngine
runtimeService,运行时服务类,org.camunda.engine.RuntimeService
repositoryService,知识库服务类,org.camunda.engine.RepositoryService
taskService,任务服务类,org.camunda.engine.TaskService
managementService,管理服务类,org.camunda.engine.ManagementService
identityService,身份服务类,org.camunda.engine.IdentityService
historyService,历史信息服务类,org.camunda.engine.HistoryService
formService,表单服务类,org.camunda.engine.FormService
|===

=== domain 类

用户、角色都需要实现camunda的identity接口。

BaseUser类的id改为String，使用uuid替代自增.多了三个属性firstName,lastName,email。原类中的realname属性不再需要，生成的工程中没有剔除，视项目情况大家手动处理。

BaseRole类增加了name属性，原类中的description属性不再需要，生成的工程中没有剔除，视项目情况大家手动处理。

=== application.yml

在application.yml增加了如下属性:
[source,yml]
----
base:
    camunda:
      processEngineName: camundaProcessEngine
      databaseSchemaUpdate: create   #  create-drop , true ,false ，create 中的一个
      deploymentName: gbDeploymentName
      deploymentResources: file:./src/main/resources/**/camunda/**/*.bpmn*.xml , file:./src/main/resources/**/camunda/**/*.png , file:./src/main/resources/**/camunda/**/*.form
      jobExecutorActivate: false
      history: audit    #归档类型 none、activity、audit、full 四种类型
      mailServerHost: mail.email.com
      mailServerPort: 25
      mailServerUsername: user@email.com
      mailServerPassword: pass
      mailServerDefaultFrom: user@email.com
      #disableCustomPreVariableTypes: true
      databaseType: h2  # 数据库类型支持 db2, h2 ,hsql ,mssql,mysql, oracle,postgres
----

其中的deploymentResources 指扫描相关路径的文件，使用“,”分隔 , 建议在生成环境设置为/ 字符

=== 流程部署及控制

根据deploymentResources扫描路径自动部署流程,默认在resources\templates\camunda目录中的流程自动部署。

默认有一个vacationRequest请假单流程,

可以通过admin/admin登录系统后，进入流程管理菜单，点击部署按钮，可在线部署xml流程（bar文件也可）

/camundaMonitor/index 是流程管理界面

也可以在线通过model设计进行保存，并在线部署。

==== 控制界面

===== 代办任务

/camundaTask/index 是代办任务的地址

/camundaTask/canStart 是可启动流程列表的地址

==== 流程示例

默认有一个vacationRequest请假单流程,

[source,yml]
----
# 请假流程
resources\templates\camunda\vacationRequest.xml
resources\templates\camunda\vacationRequest.png

# 请假domain类

domain\demo\VacationRequest.groovy

# 请假controller类（默认约定表单提交到流程自己的controller处理）

controller\demo\VacationRequestController.groovy

# 请假的节点表单 (其中的xxx为流程xml中的userTask的id名，默认约定使用_作为文件名开始字符)
web-app\WEB-INF\jsp\camundaForm\${流程名称}\_xxx.jsp
----

=== 新工作流程的制作步骤

==== 开发业务流程

使用eclipse或camunda designer 设计工作流xml

==== 创建流程domain类

创建流程domain类

==== 创建流程controller类

创建流程controller类，用于处理数据保存和流程执行。

==== 创建流程节点的jsp页面

为每个流程节点画jsp页面